services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

      Jojotique\JWT\Resources\JWTBuilder:
        public: true

      Jojotique\JWT\Resources\JWTValidationHelper:
        public: true

      Jojotique\JWT\Resources\JWTApiAuthorization:
        public: true
        arguments:
          $JWTValidationHelper: '@Jojotique\JWT\Resources\JWTBuilder'

      Jojotique\JWT\Resources\JsonWebToken:
        autowire: false
        public: true
